### PR TITLE
Code improvements

### PR DESCRIPTION
**Pull request by MarcinWieczorek**

### CODE REVIEW

**Comment by Deryllium** [comment]
Wonderful. Thank you for contributing. I will be updating this repository with yet more improvements.

**Comment by MarcinWieczorek** [comment]
I come from here btw.
https://bukkit.org/threads/can-someone-update-this-too-1-8-1-8-9.413844/

Please make sure your Maven repository is working properly.

**Comment by Deryllium** [comment]
Working on it I'll host a maven repository on github.

**Comment by MarcinWieczorek** [comment]
Wanna use mine? I wouldn't give you write access tho.

**Comment by Deryllium** [comment]
I'll stick with GitHub until I set up my own ci. Thanks for the offer though.

**Pull request merged**
